# Generated by Django 2.2.6 on 2019-12-14 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
    ]
